### ISSUE TITLE
Support ModelMetadata endpoint

### ISSUE THREAD

**Issue by njhill** [kserve/rest-proxy#14]
From the [KServe V2 Predict API](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md):

#### Model Metadata:

`GET v2/models/${MODEL_NAME}[/versions/${MODEL_VERSION}]`

Details of the REST API are [here](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#model-metadata) and corresponding gRPC API [here](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#model-metadata-1).

**Comment by rachitchauhan43** [comment]
@njhill : Do you have any docs regarding what exactly you are looking for in model metadata ? Or, maybe if you can put more details into this issue, that would be great.

I also had the same requirement. 
For my use case what we are looking for is 
1. How would a user know with what inputs the ISVC endpoint has to be called ?
2. How would user know what outputs ISVC endpoint would return ?


Few ideas I had were:
1. If a model is written using a serving runtime, then that particular serving runtime,  should have implemented an endpoint like `/get_metadata` so that any model which is deployed using that serving runtime will always have model metadata endpoint that users can use to see i/p &o/p contracts. 
But this approach would fail when someone writes a custom predictor.
2. In case of a custom predictor, we have multiple options:
  - Either we can mention the metadata as part of ISVC YAML and make it queryable like seldon does [here](https://docs.seldon.io/projects/seldon-core/en/latest/reference/apis/metadata.html#overwrite-via-environmental-variable), OR
  - We tell users to create another endpoint inside their custom predictor as mentioned here in this [thread in kserve cmty channel](https://kubeflow.slack.com/archives/CH6E58LNP/p1659441101448379)

Let me know your thoughts on this.

**Comment by njhill** [comment]
@rachitchauhan43 I'm just talking about extending the grpc-gateway in to cover the existing KServe V2 predict API Model Metadata endpoint in addition to passing through the Infer call:

`GET v2/models/${MODEL_NAME}[/versions/${MODEL_VERSION}]`

Details of the REST API are [here](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#model-metadata) and corresponding gRPC API [here](https://github.com/kserve/kserve/blob/master/docs/predict-api/v2/required_api.md#model-metadata-1).

You're right that this assumes that the model runtime in question supports this API, for now custom runtimes would also need to implement.

I'll update the PR description to clarify a bit!
